title: GitHub Pages Website
description: Assignment 1 - Website created using Github pages and Jekyll
theme: jekyll-theme-Slate

header_pages:
  - index.html
  - about.html
  - projects.html
  - contact.html
  - blog.html

# Define universal defaults
defaults:
  - scope:
      path: ""         
      type: "pages"     
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
