title: GitHub Pages Website
description: Assignment 1 - Website created using Github pages and Jekyll
theme: jekyll-theme-mordenist

header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md
  - blog.md
